require "skela.options"
require "skela.keymaps"
require "skela.plugins"
require "skela.theme"
require "skela.telescope"
require "skela.nvim-tree"
require "skela.lsp"
require "skela.treesitter"
require "skela.completion"
require "skela.commenting"
require "skela.terminal"

