$lock_cmd = pidof hyprlock || hyprlock
$turn_on_screen_cmd = hyprctl dispatch dpms on
$check_lock_and_turn_off_screen = ~/.config/hypr/scripts/check_lock_and_dpms.sh

general {
	lock_cmd = $lock_cmd
	before_sleep_cmd = $lock_cmd
	after_sleep_cmd = $turn_on_screen_cmd
	inhibit_sleep = 3
}

# No auto-lock, no auto-monitor-sleep.
# But if manually locked, turn monitors off after 10s.
listener {
	timeout = 10
	on-timeout = $check_lock_and_turn_off_screen
	on-resume = $turn_on_screen_cmd
	ignore_inhibit = false
}
