theme {
    color_scheme = KvDark
    style = kvantum-dark
    # icon_theme = <% opt.icon_theme %>
    # font = <% opt.font %>
    # font_fixed = <% opt.term_font %>
    font_size = 11
    font_fixed_size = 11
}
